name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-15
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.0
        with:
          components: clippy,rustfmt

      - run: cargo fmt --all -- --check
        if: matrix.runner == 'ubuntu-24.04'
      - run: cargo clippy --locked --all-targets --all-features -- -D warnings
        if: matrix.runner == 'ubuntu-24.04'
      - run: cargo package --locked
        if: matrix.runner == 'ubuntu-24.04'
      - run: cargo test --locked --all-features
      - run: cargo bench --locked --bench seqio_gz -- --test
        if: matrix.runner == 'ubuntu-24.04'
